name: UI Build
on:
  push:
    branches:
      - master
    paths:
      - 'ui/**'
  pull_request:
    paths:
      - 'ui/**'
  workflow_dispatch:

jobs:
  build-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install Dependencies
      working-directory: ui
      run: npm ci

    - name: Build UI
      working-directory: ui
      run: npm run build

    - name: Commit changes to PR
      if: github.event_name == 'pull_request'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Skip if commit is from the bot
        if [[ "${{ github.event.head_commit.author.name }}" == "github-actions[bot]" ]]; then
          echo "Skipping bot commit"
          exit 0
        fi
        
        # Define header files in an array for better maintainability
        HEADER_FILES=(
          "src/ui_bundle_css.h"
          "src/ui_index_html.h"
          "src/ui_index_js.h"
        )
        
        # Add files and handle errors
        for file in "${HEADER_FILES[@]}"; do
          if [[ -f "$file" ]]; then
            git add "$file"
          else
            echo "Warning: $file not found"
          fi
        done
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -m "chore: update UI build outputs [skip ci]" || exit 1
          git push || exit 1
        fi
    - name: Create Pull Request
      if: github.event_name != 'pull_request'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'chore: update UI build outputs'
        title: 'Update UI build outputs'
        body: |
          This PR updates the UI build outputs (header files) based on changes in the UI source code.

          Changes were automatically generated by the UI build workflow.
        branch: update-ui-build
        delete-branch: true
        base: master
        add-paths: |
          src/ui_bundle_css.h
          src/ui_index_html.h
          src/ui_index_js.h
        labels: |
          automated pr
          ui
